pipeline {
	agent {
	    docker {
		image 'ubuntu:latest'
		args  '-it'
	    }
		steps {
			sh 'touch test.txt'
		}
	}
	stages {
		stage("test") {
			steps {
			sh 'echo testing && touch test.txt'
			}
		}
	}
}	
